pub mod error;
pub mod result;

mod annex_a2;
mod annex_c;
mod demuxer;
mod descriptor;
mod duration_fmt;
mod header;
mod iso_639;
mod packet;
mod pcr;
mod pes;
mod pid;
mod rational;
mod section;
mod stream_type;
mod subtable_id;
mod table_id;

pub use demuxer::{Demuxer, DemuxerEvents, Packet as DemuxedPacket, Table as DemuxedTable};
pub use duration_fmt::DurationFmt;
pub use packet::Packet;
pub use pes::PES;
pub use pid::PID;
pub use result::Result;
pub use section::Bufer;
pub use section::{EIT, PAT, PMT, SDT};
pub use stream_type::StreamType;
pub use subtable_id::SubtableID;
pub use table_id::TableID;
